### ISSUE TITLE
Детальная инструкция по использованию

### ISSUE THREAD

**Issue by mr-scrpt** [greybax/cyrillic-to-translit-js#135]
Здравствуйте. Подскажите как правильно использовать библиотеку? Мне нужно применить ее в тайпскрипте. Делаю так:
`import cyrillicToTranslit from 'cyrillic-to-translit-js';` - вроде в ТС можно использовать только именованный импорт, но подключить по другому не получается 
`import * as cyrillicToTranslit from 'cyrillic-to-translit-js';`
`import {cyrillicToTranslit} from 'cyrillic-to-translit-js';`
Если подключить как в первом варианте, то хотя бы ошибки нет на этом этапе. Дале делают так
```
const transliter = new cyrillicToTranslit();
transliter.transform('тесет', "-")
```
Получаю ошибку
**cyrillic_to_translit_js_1.default is not a constructor**
Я так понимаю, что дело в неправильном импорте. Вы не могли бы подсказать как правильно использовать библиотеку в ТС. Можно добавить инструкцию, а то там пропущена часть с созданием экземпляра класса, хотя про конструктор информация есть, хотелось бы более полного описания

**Comment by bibblebabl** [comment]
Кажется, авторы просто ушли в закат :)

**Comment by bibblebabl** [comment]
@mr-scrpt импортируйте default 

```js
import CyrillicToTranslit from 'cyrillic-to-translit-js'

const cyrillicToTranslit = new CyrillicToTranslit() /// затем создаете инстанс 

cyrillicToTranslit.transform('Какая-то строка', '_').toLowerCase() // после чего вызываете

```

**Comment by greybax** [comment]
обновил readme
