### ISSUE TITLE
'x' is not 'x'

### ISSUE THREAD

**Issue by nitruxa** [greybax/cyrillic-to-translit-js#16]
Cyrillic `x` is not really cyrillic, is is english `x`
https://github.com/greybax/cyrillic-to-translit-js/blob/5ff90062893e20774fb3efc25a3756d40f5c73e0/CyrillicToTranslit.js#L31

after translit you will get `ar\321\205angelskaya-oblast`

**Comment by greybax** [comment]
fixed
