### ISSUE TITLE
Create UI on gh-pages

### ISSUE THREAD

**Issue by greybax** [greybax/cyrillic-to-translit-js#24]

**Comment by greybax** [comment]
Thank you for PR @rodweb! 👏 Just one thing which can be improvement here is implement setup for `spaceReplacement` parameter in UI. 
P.S 2nd argument here: https://github.com/greybax/cyrillic-to-translit-js/blob/master/CyrillicToTranslit.js#L44

**Comment by rodweb** [comment]
Did that. Also, high-five to the Frontender Magazine fella ✋

**Comment by greybax** [comment]
Thank you for contribution! ✋ Merged your changes

**Comment by greybax** [comment]
Demo page: https://greybax.github.io/cyrillic-to-translit-js
