### ISSUE TITLE
Can't build with "Create React App" for production

### ISSUE THREAD

**Issue by DexterHD** [greybax/cyrillic-to-translit-js#34]
When I'am trying to compile my CRA Application for production build I got an error:

```
reating an optimized production build...
Failed to compile.

Failed to minify the code from this file: 

        ./node_modules/cyrillic-to-translit-js/CyrillicToTranslit.js:77 

Read more here: http://bit.ly/2tRViJ9
```

**Comment by LeeTwelve** [comment]
@DexterHD the problem was solved by replacing all **let** keywords with a **var**. I think this is a bebel problem.

**Comment by greybax** [comment]
Is this issue still actual or I can close it?

**Comment by LeeTwelve** [comment]
@greybax my last build compiled was as normal with no errors

**Comment by greybax** [comment]
@LeeTwelve great! So I'll close it
