### ISSUE TITLE
Fixed error: "require is not defined" on Demo Page

### ISSUE THREAD

**Issue by greybax** [greybax/cyrillic-to-translit-js#72]
How to reproduce:

1. go to [Demo Page](https://alfilatov.com/cyrillic-to-translit-js/)
2. Enter some text in Cyrillic textbox
3. See console

**Comment by sime1** [comment]
I'll work on this

**Comment by emo8355** [comment]
I'll work on this =)

**Comment by greybax** [comment]
@sime1 did you test your solution? Seems it still doesn't work for now...

**Comment by sime1** [comment]
Yes I did try it, did you publish the new module and updated the index.html file? 

I will check again as soon as I can

**Comment by greybax** [comment]
yes, it works
