### ISSUE TITLE
develop logo

### ISSUE THREAD

**Issue by greybax** [greybax/cyrillic-to-translit-js#80]
Originally I've developed this project like a simple js function, but now it's more than function. This is the library with pretty solid logic underhood.

I believe that's a good time to create a logo for this repo :)

**Comment by Rootyjr** [comment]
I saw your issue let me know what you think about this:
![logo](https://user-images.githubusercontent.com/41842051/69928170-72a4e500-1480-11ea-866a-4ce46065ec04.png)

**Comment by greybax** [comment]
interesting idea, but I would like to propose some improvements:

* not `йс -> js`, but `жс -> js`
* I would like to suggest to remove a circle around
* can we compare how this logo will be in a row not in a column?

**Comment by greybax** [comment]
@Rootyjr any ideas? :)

**Comment by Rootyjr** [comment]
I'm sorry, I forgot with finals and everything. everything is doable except 3, I was a little confused about what you meant by that.

**Comment by greybax** [comment]
@Rootyjr I meant:
now it is like:
```
йс
->
js
```
I would suggest comparing with case if it will be like:
```
йс->js
```

**Comment by Rootyjr** [comment]
So something like this? 
![translit2](https://user-images.githubusercontent.com/41842051/70558806-3b52ca00-1b4b-11ea-8a26-0c8b418fc15c.png)

**Comment by greybax** [comment]
@Rootyjr looks better to me. Could you please generate some different size/resolutions for this logo?

**Comment by Rootyjr** [comment]
![translit-256w](https://user-images.githubusercontent.com/41842051/70685658-aeedf780-1c6f-11ea-8550-8547af5f74c7.png)
![translit-512w](https://user-images.githubusercontent.com/41842051/70685659-aeedf780-1c6f-11ea-8b2f-f518cc31169a.png)
![translit-1024](https://user-images.githubusercontent.com/41842051/70685662-af868e00-1c6f-11ea-9553-b2753ac79126.png)
![translit-512](https://user-images.githubusercontent.com/41842051/70685663-af868e00-1c6f-11ea-9447-bb94fd714820.png)
![translit-256](https://user-images.githubusercontent.com/41842051/70685664-af868e00-1c6f-11ea-8fa0-719fe7fec980.png)
![translit-128](https://user-images.githubusercontent.com/41842051/70685665-af868e00-1c6f-11ea-82e2-fcbd8cd89c34.png)

**Comment by Rootyjr** [comment]
translit-sizew are one where the aspect ratio is the width and height of the logo. Other sizes are centered in a square with the dimensions of the number.

**Comment by greybax** [comment]
Sounds good! Do you have a vector image (.svg) also?

**Comment by Rootyjr** [comment]
[Translit2.zip](https://github.com/greybax/cyrillic-to-translit-js/files/3954218/Translit2.zip)
Can't upload .svg directly. It's in the .zip

**Comment by greybax** [comment]
Great! It would be awesome if you would send a PR with all these images into the `images` folder. But if you are not familiar with sending pull request I'm ok, just up to you :)

**Comment by Rootyjr** [comment]
https://github.com/greybax/cyrillic-to-translit-js/pull/84
Done.
