### ISSUE TITLE
The symbols which "cyrillic-to-translit-js' do not replace

### ISSUE THREAD

**Issue by expdevelop** [greybax/cyrillic-to-translit-js#9]
Hi guys, I've found the bug:
The symbols `ь ъ ы э х` will be not replaced.

I've solved this problem, maybe it can help someone.
```js
return cyrillicToTranslit()
    .transform(string)
    .replace(/ь?ъ/gi, '')
    .replace(/э/gi, 'e')
    .replace(/ы/gi, 'i')
    .replace(/х/gi, 'h')
```

**Comment by greybax** [comment]
Hi @expdevelop 

Could you please to do PR with this fix?

**Comment by greybax** [comment]
Fixed

**Comment by expdevelop** [comment]
Have no idea about PR, sorry :)

So the problem was solved and we should close this, thanks for your work.

**Comment by vasilievruslan** [comment]
`Сыры => siri => сири` не правильно меняет букву ы

**Comment by greybax** [comment]
@vasilievruslan `Сыры => syry => ?` так лучше?
